### ISSUE TITLE
How to call a Future function?

### ISSUE THREAD

**Issue by biniama** [kuromukira/flutter_splash#1]
Hello,

I appreciate that you improved the SplashScreen package. I am using it to call a future function/method that downloads data from the cloud. 
Questions: 
1. Is this the right way to do it?
2. This function is bring called twice for some reason. Why could it be?

```
loadWidget() async {
      return await _myService.downloadAllCategories().then((_) => AfterSplash());
 }

  @override
  Widget build(BuildContext context) {
    return new Splash(
      navigateAfterFuture: loadWidget(),
      title: new Text(
        'Welcome In SplashScreen',
        style: new TextStyle(fontWeight: FontWeight.bold, fontSize: 20.0),
      ),
      image: new Image.network(
          'https://flutter.io/images/catalog-widget-placeholder.png'),
      backgroundColor: Colors.white,
      styleTextUnderTheLoader: new TextStyle(),
      photoSize: 100.0,
      onClick: () => print("Flutter Egypt"),
      loaderColor: Colors.red,
    );
  }
```

Here is my log
```
I/flutter (13967): in loadWidget()
I/flutter (13967): making api call
I/flutter (13967): in loadWidget()
I/flutter (13967): making api call
```

**Comment by norarrsgd** [comment]
Hi, sorry you had this kind of issue. There might be a possibility that your Splash widget has been rendered twice 🤔

**Comment by forever84721** [comment]
I fixed this problem, Please confirm this PR.#3

**Comment by norarrsgd** [comment]
Hi @biniama, I will be creating a release later today. Will close this issue once deployed.

Credits to  @forever84721 for fixing 🍻
