### ISSUE TITLE
navigateAfterFuture is being called twice

### ISSUE THREAD

**Issue by emersonsiega** [kuromukira/flutter_splash#2]
I'm passing an asynchronous function to `navigateAfterFuture`:
```dart
navigateAfterFuture: _doSomething(),
```

```dart
Future<String> _doSomething() async { ... }
```

It seems like the `navigateAfterFuture` is being called twice. 
The first call is done at:
`if (widget.navigateAfterFuture == null) {`
And the second call is done in the right place:
`widget.navigateAfterFuture.then((navigateTo) {`

Maybe the `navigateAfterFuture` parameter could be a `function` instead of a `Future<dynamic>`

If there's a correct way to pass this parameter, please let me know.

**Comment by norarrsgd** [comment]
Hello, thank you for your feedback. Please know that this project is also accepting PRs.

**Comment by emersonsiega** [comment]
@kuromukira  I do not have much free time right now for a PR, but I've just created a simple example.

If you run this code at dartpad, you will see that `myFunction` runs just once.

```dart
import 'dart:async';

void main() {
  test(
    navigateAfterFuture: myFunction,
  );
}

Future<String> myFunction() async {
  return "myFunction :)";
}

void test({
  Future<String> Function() navigateAfterFuture,
}) async {
  if (navigateAfterFuture != null) {
    final response = await navigateAfterFuture();
    print(response);
  }
}
```

**Comment by forever84721** [comment]
I fixed this problem, Please confirm this PR.#3

**Comment by norarrsgd** [comment]
Hi @emersonsiega, I will be creating a release later today. Will close this issue once deployed.

Credits to  @forever84721 for fixing 🍻
